--46--

CREATE OR REPLACE TYPE Kocury
AS OBJECT(
	imie VARCHAR2(15),
	plec VARCHAR2(1),
	pseudo VARCHAR2(15),
	funkcja VARCHAR2(10),
	szef VARCHAR2(15),
	w_stadku_od DATE,
	przydzial_myszy NUMBER(3),
	myszy_extra NUMBER(3),
	nr_bandy NUMBER(2),
	MEMBER FUNCTION RETURN ,
	MAP MEMBER FUNCTION Compare RETURN VARCHAR2);
	
CREATE OR REPLACE TYPE BODY Kocury
AS
	MAP MEMBER FUNCTION Compare RETURN VARCHAR2 IS
	BEGIN
		RETURN imie || pseudo;
	END;
END;

CREATE OR REPLACE TYPE Wrogowie_Kocurow
AS OBJECT(
	kot REF Kocury,
	imie_wroga VARCHAR2(15),
	data_incydentu DATE,
	opis_incydentu VARCHAR2(50),
	MEMBER FUNCTION RETURN ,
	MAP MEMBER FUNCTION Compare RETURN VARCHAR2);
	
CREATE OR REPLACE TYPE BODY Wrogowie_Kocurow
AS
	MAP MEMBER FUNCTION Compare RETURN VARCHAR2 IS
	BEGIN
		RETURN kot.Compare() || imie_wroga;
	END;
END;
	
CREATE OR REPLACE TYPE Konto
AS OBJECT(
	nr_myszy NUMBER(10),
	wlasciciel REF Elita,
	data_wprowadzenia DATE,
	data_usuniecia DATE,
	MEMBER FUNCTION RETURN ,
	MAP MEMBER FUNCTION Compare RETURN VARCHAR2);

CREATE OR REPLACE TYPE BODY Konto
AS
	MAP MEMBER FUNCTION Compare RETURN VARCHAR2 IS
	BEGIN
		RETURN wlasciciel.Compare() || LPAD(TO_CHAR(nr_myszy, 10, ' '));
	END;
END;
	
CREATE OR REPLACE TYPE Elita
AS OBJECT(
	kot REF Kocury,
	sluga REF Plebs,
	MEMBER FUNCTION RETURN ,
	MAP MEMBER FUNCTION Compare RETURN VARCHAR2);

CREATE OR REPLACE TYPE BODY Elita
AS
	MAP MEMBER FUNCTION Compare RETURN VARCHAR2 IS
	BEGIN
		RETURN ;
	END;
END;
	
CREATE OR REPLACE TYPE Plebs
AS OBJECT(
	kot REF Kocury,
	MEMBER FUNCTION RETURN ,
	MAP MEMBER FUNCTION Compare RETURN VARCHAR2);

CREATE OR REPLACE TYPE BODY Plebs
AS
	MAP MEMBER FUNCTION Compare RETURN VARCHAR2 IS
	BEGIN
		RETURN ;
	END;
END;
